[package]
name = "bake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
regex = "1"
libc = "0.2"
curl = "0.4"
anyhow = "1"
thiserror = "1"
